version: '3'


volumes:
  DB:

services:

  db:
    image: postgres
    volumes:
      - DB:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - ${DB_PORT}:5432
  web:
    build: .
    command: python3 wsgi.py
    volumes:
      - .:/EyeOfTeacher
    ports:
      - ${WEB_PORT}:5000
